import { StyleSheet, Dimensions } from "react-native";

let { width, height } = Dimensions.get("window");
let tabWidth = width / 4;
let smallScreenText = 12;
let mediumScreenText = 16;
let largeScreenText = 20;

let textStyle = smallScreenText;

if (width >= 380 && width <= 600) {
  textStyle = mediumScreenText;
} else if (width > 600) {
  textStyle = largeScreenText;
}

// ─── CrewLoop Brand Colors ────────────────────────────────────────────────────
// Primary:  #1B3A6B  (deep navy blue)
// Accent:   #F47C20  (orange)
// Dark bg:  #1E2530  (near-black blue-grey)
// Surface:  #2C3444  (elevated surface)
// Muted:    #8A95A3  (muted text / placeholders)
// ─────────────────────────────────────────────────────────────────────────────

export default StyleSheet.create({
  avatarIcon: {
    backgroundColor: "#1B3A6B",
    marginRight: 10,
  },
  avatarIconBtn: {
    backgroundColor: "#F47C20",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  avatarIconImage: {
    backgroundColor: "#F47C20",
  },
  avatarIconCheckout: {
    backgroundColor: "#1B3A6B",
    marginRight: width * 0.03,
  },
  buttonText: {
    color: "#ffffff",
    fontSize: textStyle,
    fontWeight: "600",
  },
  backButton: {
    position: "absolute",
    left: 5,
    bottom: "10%",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  badgeView: {
    position: "absolute",
    right: tabWidth / 5,
  },
  checkInOutBtn: {
    width: width * 0.6,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: height * 0.025,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  checkoutFormBtns: {
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  checkoutRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  checkoutColumn: {
    flexDirection: "column",
    alignItems: "center",
    margin: 20,
  },
  chip: {
    backgroundColor: "#1B3A6B",
    margin: "1%",
    borderRadius: 15,
  },
  closeButton: {
    position: "absolute",
    right: 10,
    top: 10,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  columnView: { flex: 1, flexDirection: "column" },
  compJobCard: {
    backgroundColor: "#2C3444",
    marginBottom: height * 0.02,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  contactIcon: {
    width: width / 20,
    marginLeft: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  containerRowView: {
    flex: 1,
    flexDirection: "row",
    width: "90%",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "3%",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#1E2530",
    alignItems: "center",
    paddingHorizontal: width * 0.05,
  },
  dropdownTextStyles: {
    color: "#ffffff",
  },
  fileIconRow: { padding: 10 },
  fileTextRow: { width: "85%", paddingRight: 10 },
  formLine: {
    borderBottomColor: "#8A95A3",
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  fpForm: {
    flex: 3,
    width: "100%",
    maxHeight: height * 0.7,
    marginTop: "5%",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  fpSubmitBtn: {
    width: width / 1.5,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    marginTop: height * 0.08,
    marginBottom: 25,
    height: height * 0.08,
    alignItems: "center",
    justifyContent: "center",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  fpText: {
    color: "#ffffff",
    fontSize: textStyle,
    justifyContent: "flex-start",
    marginTop: height * 0.05,
  },
  fpValMessageText: {
    color: "#FF6B6B",
    width: width * 0.65,
    marginTop: height * 0.1,
  },
  header: {
    alignItems: "center",
    marginBottom: height * 0.03,
  },
  horizontalRule: {
    flex: 1,
    height: 1,
    backgroundColor: "#8A95A3",
    marginBottom: 10,
    marginTop: 15,
  },
  image: { height: height * 0.2 },
  inputView: {
    width: width * 0.8,
    backgroundColor: "#2C3444",
    borderRadius: 15,
    height: height * 0.06,
    paddingLeft: width * 0.05,
    color: "#ffffff",
    fontSize: textStyle,
    marginBottom: height * 0.02,
  },
  inputAreaView: {
    width: width * 0.8,
    backgroundColor: "#2C3444",
    borderRadius: 15,
    minHeight: height * 0.2,
    paddingLeft: width * 0.05,
    color: "#ffffff",
    fontSize: textStyle,
    marginBottom: height * 0.02,
    textAlignVertical: "top",
  },
  jobCard: {
    backgroundColor: "#2C3444",
    marginBottom: height * 0.02,
    width: "100%",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  jobCardContent: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginBottom: height * 0.01,
  },
  jobCardContentLabel: {
    fontSize: textStyle,
    fontWeight: "bold",
  },
  jobCardContentTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: textStyle,
    fontWeight: "bold",
  },
  jobCardContentTitleSub: {
    flex: 1,
    textAlign: "center",
    fontSize: textStyle - 1,
  },
  jobCardContentText: {
    fontSize: textStyle - 1,
  },
  jobCardTouchable: {
    width: "100%",
  },
  jobNavIcon: {
    flex: 1,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 2,
    shadowOpacity: 0.1,
  },
  jobNavContent: {
    marginVertical: height * 0.03,
    flexGrow: 1,
    backgroundColor: "#1E2530",
    alignItems: "center",
  },
  labelView: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  loginBtn: {
    width: width * 0.6,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.05,
    marginBottom: height * 0.05,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  loginForm: {
    flex: 2,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  loginFormButtons: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "space-evenly",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  loginTitle: {
    fontWeight: "bold",
    fontSize: 40,
    color: "#ffffff",
    textAlign: "center",
    marginVertical: height * 0.03,
  },
  loginLogo: {
    flexShrink: 1,
    width: "auto",
    minWidth: "100%",
    minHeight: height * 0.1,
  },
  logo: {
    flexShrink: 1,
    width: "auto",
    minWidth: "100%",
    minHeight: height * 0.08,
    marginBottom: height * 0.03,
  },
  logoutBtn: {
    width: width * 0.6,
    backgroundColor: "#2C3444",
    borderRadius: 20,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.02,
    marginBottom: height * 0.02,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  logoutBtnText: {
    color: "#ffffff",
    fontSize: textStyle,
  },
  modalPopup: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: width * 0.05,
  },
  modalPopupContent: {
    alignItems: "center",
    backgroundColor: "#2C3444",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 560,
    maxHeight: height * 0.8,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalScroll: {
    width: "100%",
  },
  modalScrollContent: {
    alignItems: "center",
    paddingBottom: 16,
  },
  passwordInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  passwordVisibilityButton: {
    position: "absolute",
    right: width * 0.03,
    bottom: height * 0.02,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  photoImage: {
    marginTop: 15,
  },
  profileForm: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  profileFormButtons: {
    flex: 2,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    elevation: 10,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  profileLable: { alignSelf: "flex-start", paddingLeft: 20 },
  profilePic: {
    flexShrink: 1,
    width: "auto",
  },
  rowView: {
    flexDirection: "row",
    alignItems: "center",
  },
  SafeArea: {
    flex: 1,
    backgroundColor: "#1E2530",
    paddingTop: 15,
    paddingBottom: 15,
  },
  segmentedBtn: {
    width: width * 0.7,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    borderColor: "#F47C20",
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
    marginTop: height * 0.02,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
  },
  signatureModal: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#1E2530",
  },
  signatureView: {
    alignItems: "center",
    justifyContent: "center",
    height: width,
    width: height,
    padding: 10,
    backgroundColor: "#2C3444",
    transform: [{ rotate: "270deg" }],
  },
  signatureRow: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    alignItems: "center",
  },
  signupText: {
    color: "#F47C20",
    fontSize: textStyle,
    justifyContent: "flex-start",
  },
  stagingBannerText: { color: "white", fontSize: textStyle },
  stagingBannerView: {
    top: 0,
    backgroundColor: "#1B3A6B",
    paddingTop: height / 20,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtn: {
    width: width * 0.6,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
    marginTop: height * 0.02,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnAttachment: {
    width: width * 0.6,
    backgroundColor: "#F47C20",
    borderRadius: 20,
    height: height * 0.07,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    marginBottom: height * 0.025,
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  switch: {
    elevation: 6,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 6,
    shadowOpacity: 0.25,
  },
  switchLabel: {
    width: width * 0.6,
    color: "#ffffff",
    fontSize: textStyle,
    marginTop: height * 0.015,
  },
  tabNavIcons: {
    tabBarIndicatorStyle: { backgroundColor: "#F47C20" },
    tabBarActiveTintColor: "#F47C20",
    tabBarInactiveTintColor: "#8A95A3",
    tabBarStyle: {
      backgroundColor: "#1E2530",
    },
    tabBarAllowFontScaling: true,
    tabBarLabelStyle: { fontSize: textStyle - 1 },
  },
  tabBarBadge: {
    color: "#ffffff",
    backgroundColor: "#FF6B6B",
    paddingHorizontal: textStyle * 0.3,
    borderRadius: 50,
  },
  Text: {
    color: "#ffffff",
    fontSize: textStyle,
    justifyContent: "flex-start",
  },
  TextTitle: {
    color: "#ffffff",
    fontSize: textStyle + 5,
    justifyContent: "flex-start",
  },
  TextDescript: {
    color: "#D3D3D3",
    fontSize: textStyle,
  },
  textMuted: { color: "#8A95A3" },
  thumbnailView: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  TextVersion: {
    color: "#8A95A3",
    fontSize: 10,
    justifyContent: "flex-start",
  },
  valMessageText: {
    color: "#FF6B6B",
  },
  workLogComment: {
    flexGrow: 1,
    backgroundColor: "#1E2530",
    alignSelf: "flex-start",
    marginBottom: 15,
  },
});
